name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main に push で発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Node.js セットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係インストール
        run: cd frontend/nextjs && npm install

      - name: 静的ファイル出力
        env:
          GITHUB_PAGES: true
          NEXT_PUBLIC_USERPOOL_ID: ${{ secrets.NEXT_PUBLIC_USERPOOL_ID }}
          NEXT_PUBLIC_APPCLIENT_ID: ${{ secrets.NEXT_PUBLIC_APPCLIENT_ID }}
        run: cd frontend/nextjs && npm run deploy

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/nextjs/out
